### ISSUE TITLE
Fork and Hugo static website

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#1]
Please put link to your Hugo static website below

e.g.
+ NIT 0000000
+ url https://rrkurnova.github.io/lecture-notes

**Comment by NeganSmith92** [comment]
(+) NIT : 21181300
(+) url : https://negansmith92.github.io/lecture-notes/0048

**Comment by NerdyVandheka** [comment]
(-) NIT 21181213
(-) URL https://nerdyvandheka.github.io/lecture-notes/
            https://nerdyvandheka.github.io/lecture-notes/0048/

**Comment by charlesmana** [comment]
NIT 21181068
URL : https://charlesmana.github.io/lecture-notes/

**Comment by CyberianRonin** [comment]
NIT : 21181213
url : https://cyberianronin.github.io/lecture-notes/

**Comment by CyberianRonin** [comment]
(-) NIT : 21181229
(-) URL : https://cyberianronin.github.io/lecture-notes/

**Comment by yunoooo111** [comment]
NIT = 21181296
https://yunoooo111.github.io/lecture-notes/0048/

**Comment by c4t4r** [comment]
(-) NIT : 21181074
(-) URL : https://c4t4r.github.io/lecture-notes/0048/

**Comment by ayarayenima** [comment]
NIT : 21181032
URL : https://ayarayenima.github.io/lecture-notes/0048/#first-section

**Comment by Ptolemu5** [comment]
NIT = 21181203
URL = https://ptolemu5.github.io/lecture-notes/0048/

**Comment by narapatimulia** [comment]
*NIT :  21181195
*url : https://narapatimulia.github.io/lecture-notes/0048/

**Comment by birongzah** [comment]
NIT : 21181241
URL : https://birongzah.github.io/lecture-notes/0048/

**Comment by ayodyaadhi01** [comment]
NIT : 21181017
URL : https://ayodyaadhi01.github.io/lecture-notes/

**Comment by MazamGanendra** [comment]
NIT : 21181192
url https://mazamganendra.github.io/lecture-notes/

**Comment by CriticalOlymp** [comment]
NIT : 21181064
URL : https://criticalolymp.github.io/lecture-notes/0048/

**Comment by tegarhermans** [comment]
NIT : 21181284
URL : https://tegarhermans.github.io/lecture-notes/sergeant
