### ISSUE TITLE
GoogleorganicResultsScraper.js

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#11]
+ Download [`GoogleorganicResultsScraper.js`](https://github.com/Darshan972/GoogleScrapingBlogs/blob/main/GoogleorganicResultsScraper.js).
+ Execute it without modification.
+ Report the output here.

**Comment by afrozhie** [comment]
![image](https://github.com/dudung/lecture-notes/assets/116063782/06954a94-e404-4a2c-a292-449f8a4d591e)

**Comment by MazamGanendra** [comment]
Mazam Ganendra
![11](https://github.com/dudung/lecture-notes/assets/144425268/a588fedc-7f65-48de-bbc4-0f906daf5f83)

**Comment by CyberianRonin** [comment]
![Screenshot (380)](https://github.com/dudung/lecture-notes/assets/122846418/eded14df-b4a1-458c-8d56-b21627fc7c22)

**Comment by c4t4r** [comment]
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/122764330/e68582f4-673c-4a9f-90ea-35e8f0e3bf4d">

**Comment by CriticalOlymp** [comment]
![Screenshot 2023-10-20 132541](https://github.com/dudung/lecture-notes/assets/144425203/44c9ecb9-5128-4d5c-b85c-d4bbf87ffec7)

**Comment by NerdyVandheka** [comment]
![Screenshot 2023-10-20 132629](https://github.com/dudung/lecture-notes/assets/144425376/516c2217-ebe5-4a87-b647-1ec1498a234d)

**Comment by birongzah** [comment]
<img width="402" alt="Screenshot 2023-10-20 at 13 33 12" src="https://github.com/dudung/lecture-notes/assets/144424494/d98b9832-40e8-4467-b0ec-4b3c08f8af9a">

**Comment by NeganSmith92** [comment]
<img width="509" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/7ed5df7c-275d-4fe9-aa9a-42dd109abf4b">

**Comment by yunoooo111** [comment]
![Uploading guluguluscraping.png…]()

**Comment by yunoooo111** [comment]
![guluguluscraping](https://github.com/dudung/lecture-notes/assets/113901717/6f55ece1-612e-48bc-bc65-5798baf9a221)

**Comment by tegarhermans** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425283/5c961a90-4d6e-4631-8985-342b7757d003)

**Comment by Ptolemu5** [comment]
![Screenshot 2023-10-20 114427](https://github.com/dudung/lecture-notes/assets/144424941/102a81da-b002-4a41-894c-7a1a29895d00)

**Comment by Ptolemu5** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424941/9a546c9d-9f02-4fe9-b10a-f65682d9c4e8)

**Comment by IZAN0R** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424895/e961f9c8-a731-4eb1-85c0-f7e50bd2220e)

**Comment by ayodyaadhi01** [comment]
<img width="960" alt="Screenshot 2023-10-20 135651" src="https://github.com/dudung/lecture-notes/assets/144425145/3163184e-f628-4008-bedf-d27d96be4e42">

**Comment by irhwam** [comment]
<img width="488" alt="Screenshot 2023-10-20 135842" src="https://github.com/dudung/lecture-notes/assets/144425029/89514c3c-0288-46b9-ab2e-fd16064762ad">

**Comment by charlesmana** [comment]
<img width="493" alt="image" src="https://github.com/dudung/lecture-notes/assets/114788396/1edb3b95-2434-4715-9447-71fd05702121">

**Comment by narapatimulia** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424964/d6978d03-385e-4fb3-9195-de566f180bce)

**Comment by bahrudinz** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425269/a73648bf-32e9-48a1-b914-e610da3d0131)

**Comment by Antara000** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425065/ce4389ef-6ffe-4a86-9fcb-6a3477cc2647)

**Comment by ayarayenima** [comment]
<img width="672" alt="image" src="https://github.com/dudung/lecture-notes/assets/144424497/8088fac5-0572-4489-8dde-17154f74ad8d">

**Comment by yunisangadji** [comment]
<img width="709" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/b00cc7e5-3a69-4b95-a135-4fb074de638f">
