### ISSUE TITLE
Title of organic results using GoogleorganicResultsScraper.js

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#13]
+ Give here only part of the code for obtaining title of organic result. Only one line of code.
+ Give the result here showing that the titles are really scraped from the SERP.

**Comment by c4t4r** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });

<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/122764330/c8683309-b8da-4bf2-81ee-fcd7ee30d78b">

**Comment by charlesmana** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/114788396/db9f4296-9086-4afb-8caa-96f502e6551f">

**Comment by CyberianRonin** [comment]
![Screenshot (383)](https://github.com/dudung/lecture-notes/assets/122846418/143a3bef-bea9-4e9d-ae46-50821f714670)

**Comment by birongzah** [comment]
<img width="922" alt="Screenshot 2023-10-20 at 13 46 43" src="https://github.com/dudung/lecture-notes/assets/144424494/0e1d658d-78f7-44bc-914c-863de207e06b">

**Comment by birongzah** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
<img width="918" alt="Screenshot 2023-10-20 at 13 49 37" src="https://github.com/dudung/lecture-notes/assets/144424494/1830cda1-311c-4340-b1f6-ea45a8cf182e">

**Comment by NeganSmith92** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });

<img width="947" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/7c7e959b-1813-49eb-85f1-2df578c2167e">

**Comment by IZAN0R** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
![image](https://github.com/dudung/lecture-notes/assets/144424895/59c7743a-fc42-44df-9741-3fa29a5ce17e)

**Comment by yunoooo111** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });

![hasilguluscraping](https://github.com/dudung/lecture-notes/assets/113901717/facb1cc2-36cd-42e9-99f2-7017a951adee)

**Comment by NerdyVandheka** [comment]
![Screenshot 2023-10-20 140209](https://github.com/dudung/lecture-notes/assets/144425376/996f237a-eae3-4ba5-a39a-03b30a8309c0)

$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();

**Comment by IZAN0R** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();

![image](https://github.com/dudung/lecture-notes/assets/144424895/3dd47b88-1dbf-4e27-9ae3-8995f11ce2d4)

**Comment by tegarhermans** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425283/0415b38e-c271-4e53-b5c6-0c2a2aa3033b)

**Comment by ayodyaadhi01** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
<img width="960" alt="Screenshot 2023-10-20 142309" src="https://github.com/dudung/lecture-notes/assets/144425145/523abc93-8e98-490f-9af0-0674dc48ddd9">
<img width="960" alt="Screenshot 2023-10-20 142321" src="https://github.com/dudung/lecture-notes/assets/144425145/53683789-6dc7-4501-9a29-e8c03505e77b">

**Comment by CriticalOlymp** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
![Screenshot 2023-10-20 143303](https://github.com/dudung/lecture-notes/assets/144425203/3c3aab74-395d-4401-b395-6e1e2cd7ff35)

**Comment by bahrudinz** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425269/b7574419-3050-47ab-9798-1bffc67919bb)

**Comment by Antara000** [comment]
```md
$(".LC20lb").each((i, el) => {
        titles[i] = $(el).text();
      });
```
![image](https://github.com/dudung/lecture-notes/assets/144425065/4bd8d7c6-aacb-44b4-b8fe-1188a7bb12f3)

**Comment by afrozhie** [comment]
$("h3[class='LC20lb MBeuO DKV0Md']").each((i, el) => {
        titles[i] = $(el).text();
      });
![image](https://github.com/dudung/lecture-notes/assets/116063782/c845792b-b6e0-4ee0-9218-97fe0164e0c3)

**Comment by Ptolemu5** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424941/a99a1da4-eb13-4649-8c5e-bca185264756)

**Comment by ayarayenima** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
![image](https://github.com/dudung/lecture-notes/assets/144424497/79e84754-abed-46e0-893a-12adaa19c2e2)

**Comment by yunisangadji** [comment]
<img width="949" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/32474548-7f73-468d-9a8e-3607e86e2e17">

**Comment by MazamGanendra** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
![image_2023-11-03_142240460](https://github.com/dudung/lecture-notes/assets/144425268/e58f987e-73e8-44c6-a8d0-684db93f41f3)
