### ISSUE TITLE
Titles, links, snippets, displayed links of organic results using GoogleorganicResultsScraper.js

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#14]
+ Give lines of codes for obtaining titles, links, snippets, and displayed links of organic results. Only for lines.
+ Give the output showing that all information (titles, links, snippets, displayed links) are scraped from the SERP.

**Comment by c4t4r** [comment]
$('.LC20lb.MBeuO.DKV0Md').each((i, el) => {
        titles[i] = $(el).text();
      });
      $('a[jsname="UWckNb"]').each((i, el) => {
        links[i] = $(el).attr('href');
      });
      $('.VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf > span').each((i, el) => {
        snippets[i] = $(el).text();
      });
      $('.g .yuRUbf .NJjxre .tjvcx').each((i, el) => {
        displayedLinks[i] = $(el).text();
      });

<img width="960" alt="Screenshot 2023-10-20 134140" src="https://github.com/dudung/lecture-notes/assets/122764330/3b98a20f-fb32-46ba-b1a9-369e7edeb405">

**Comment by CyberianRonin** [comment]
$(".srKDX.cvP2Ce").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".yuRUbf > a").each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".g .VwiC3b ").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".g .yuRUbf .NJjxre .tjvcx").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
      
      
![Screenshot (383)](https://github.com/dudung/lecture-notes/assets/122846418/edad9314-78f8-4c6b-9df6-bcecc97fc5d4)

**Comment by charlesmana** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
	  
	$('div[class="byrV5b"]').each((i, el) => {
      //links[i] = $(el).attr('href');
	  links[i] = $(el).text();
      });
	  
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
	  
      $(".VuuXrf").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/114788396/c2b81e1c-afcf-40e1-8fe0-ef50fd04d626">

**Comment by birongzah** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
<img width="952" alt="Screenshot 2023-10-20 at 13 51 26" src="https://github.com/dudung/lecture-notes/assets/144424494/72cb2394-a622-44d8-a4cc-57cb66322fc2">

**Comment by NeganSmith92** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
      
<img width="947" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/bbe87e4a-b632-42e2-a62a-ece294c991f3">

**Comment by NerdyVandheka** [comment]
![Screenshot 2023-10-20 140209](https://github.com/dudung/lecture-notes/assets/144425376/7afacdec-978c-4d0a-8a05-65308bc7a93b)

**Comment by IZAN0R** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".yuRUbf").find("div").each((i, el) => {
        $(el).find('span a').each((j, a) => {
            links.push($(a).attr("href"));
        });
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf > span").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".g .yuRUbf .NJjxre .tjvcx").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });

![image](https://github.com/dudung/lecture-notes/assets/144424895/dbbd2236-80d6-4e8c-a720-80afb43a1980)

**Comment by NerdyVandheka** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        displayedLinks[i] = $(el).text();
![Screenshot 2023-10-20 140209](https://github.com/dudung/lecture-notes/assets/144425376/d7b72e65-b0a1-4978-afd1-95bdd91184cc)

**Comment by birongzah** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $('a[jsname="UWckNb"]').each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
<img width="928" alt="Screenshot 2023-10-20 at 14 09 29" src="https://github.com/dudung/lecture-notes/assets/144424494/9ad54c77-cfaa-40aa-9e23-ca0ca628a731">

**Comment by yunoooo111** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        //links[i] = $(el).attr("href");
		links[i] = $(el).text();
      });
      $(".IsZvec").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".byrV5b").each((i, el) => { 
        displayedLinks[i] = $(el).text();
      });

![hasilguluscraping](https://github.com/dudung/lecture-notes/assets/113901717/13ef032e-87c3-42fe-b8b9-d79c4a930ebe)

**Comment by CyberianRonin** [comment]
$(".srKDX.cvP2Ce").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".kb0PBd.cvP2Ce.jGGQ5e.ieodic> a").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".g .VwiC3b ").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".g .yuRUbf .NJjxre .tjvcx").each((i, el) => {
        displayedLinks[i] = $(el).text();
![Screenshot (384)](https://github.com/dudung/lecture-notes/assets/122846418/297750f7-438d-4785-ad8e-2857de28016c)

      });

**Comment by tegarhermans** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $('div[class=".qLRx3b.tjvcx.GvPZzd.cHaqb"]').each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![image](https://github.com/dudung/lecture-notes/assets/144425283/84dba1ce-2a77-4585-96d0-6e577a841bc5)

**Comment by yunoooo111** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $('span[class="VuuXrf"]').each((i, el) => {
        //links[i] = $(el).attr("href");
		links[i] = $(el).text();
      });
      $(".IsZvec").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".byrV5b").each((i, el) => { 
        displayedLinks[i] = $(el).text();
      });

![hasildivdata](https://github.com/dudung/lecture-notes/assets/113901717/55bff7fd-3fd1-4074-a49b-dab03d6901fb)

**Comment by CriticalOlymp** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".UWckNb").each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".kb0PBd.cvP2Ce").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![Screenshot 2023-10-20 143303](https://github.com/dudung/lecture-notes/assets/144425203/3433acbc-d9d3-4d6e-b431-33ff66fc5698)

**Comment by ayodyaadhi01** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".kb0PBd.cvP2Ce.ieodic").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
<img width="960" alt="Screenshot 2023-10-20 142309" src="https://github.com/dudung/lecture-notes/assets/144425145/1c5ed734-6ab4-4c04-8c00-0453b0d5301c">

<img width="960" alt="Screenshot 2023-10-20 142321" src="https://github.com/dudung/lecture-notes/assets/144425145/154032ac-5156-4282-83ee-c4c77a5d3cf5">

**Comment by CriticalOlymp** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $('a[jsname = "UWckNb"]').each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".kb0PBd.cvP2Ce").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![Screenshot 2023-10-20 144602](https://github.com/dudung/lecture-notes/assets/144425203/95abe35f-3ffe-4589-8c83-c98adcc41ed5)

**Comment by bahrudinz** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![image](https://github.com/dudung/lecture-notes/assets/144425269/f20dbe6c-1b92-4968-b450-1569990a061d)

**Comment by Antara000** [comment]
```md
$(".LC20lb").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".qLRx3b").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".g .VwiC3b ").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".g .yuRUbf .NJjxre .tjvcx").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
```
![image](https://github.com/dudung/lecture-notes/assets/144425065/5afc52b0-ca48-49e3-b5b1-fca0f07c0078)

**Comment by afrozhie** [comment]
$("h3[class='LC20lb MBeuO DKV0Md']").each((i, el) => {
        titles[i] = $(el).text();
      });
      $("a[jsname='UWckNb']").each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".VwiC3b > span").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $("cite[class='qLRx3b tjvcx GvPZzd cHaqb']").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });

![image](https://github.com/dudung/lecture-notes/assets/116063782/31b766cf-9a31-46db-8e6d-d3d8c3dc71cb)

**Comment by Ptolemu5** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![Screenshot 2023-10-20 153410](https://github.com/dudung/lecture-notes/assets/144424941/ea70f847-3f2b-4af3-b436-b592ac0ed226)

**Comment by yunisangadji** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
<img width="851" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/d0d4109c-4ea9-4e34-be84-504ec746bc4a">

**Comment by ayarayenima** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".UWckNb").each((i, el) => {
        links[i] = $(el).attr("href");
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".byrV5b").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });
![image](https://github.com/dudung/lecture-notes/assets/144424497/5959ced0-ded7-4bee-aadf-2da6f68ca068)

**Comment by MazamGanendra** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
        titles[i] = $(el).text();
      });
      $(".VuuXrf").each((i, el) => {
        links[i] = $(el).text();
      });
      $(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
        snippets[i] = $(el).text();
      });
      $(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
        displayedLinks[i] = $(el).text();
      });

![Screenshot 2023-11-03 142232](https://github.com/dudung/lecture-notes/assets/144425268/06655985-2348-4331-bca0-f4367b8b23c7)
