### ISSUE TITLE
Save JSON file for organic results from Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#15]
+ Write additional lines of codes for saving organic results from SERP in a JSON file.
+ Screenshot content of the JSON file.

**Comment by c4t4r** [comment]
import module "fs" first
const fs = require('fs');

and then write this code after "for" function

const jsonData = JSON.stringify(organicResults, null, 2);

      fs.writeFile('hasilscrapping.json', jsonData, (err) => {
        if (err) throw err;
        console.log('Data written to file');
      });

and the results will be created as a json file with name "hasilscrapping.json"

<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/122764330/59313bfb-4785-4fcc-8285-317bb6f3e170">

**Comment by IZAN0R** [comment]
pertama, import module "fs"
const fs = require('fs');

setelah itu, masukkan kode berikut setelah fungsi "for"
  fs.writeFile('hasil.json', jsonData, (err) => {
    if (err) throw err;
    console.log('Data has been successfully added to the file');
  });
});

![image](https://github.com/dudung/lecture-notes/assets/144424895/0ead4685-b615-4d3d-8a09-ea4d0e1ea2c8)

**Comment by NerdyVandheka** [comment]
1. Import module "fs"
const fs = require('fs');
2. Masukkan kode berikut ini setelah fungsi "for" 
const jsonData = JSON.stringify(organicResults);
     fs.writeFileSync("DeathMetalScrapping.json", jsonData);
![Screenshot 2023-10-20 144759](https://github.com/dudung/lecture-notes/assets/144425376/216e56a8-3cce-44e0-9c32-019c50865bbc)
![Screenshot 2023-10-20 144810](https://github.com/dudung/lecture-notes/assets/144425376/b234be3c-103a-4bab-bcc1-4b57db924a63)

**Comment by NeganSmith92** [comment]
first, add this syntax in the beginning

const fs = require("fs");

to import file system into the module, then add this syntax before the getOrganicdata()


fs.writeFile("organicResults.json", JSON.stringify(organicResults, null, 2), (err) => {
        if (err) {
          console.error("Error writing JSON file:", err);
        } else {
          console.log("JSON file saved successfully!");
        }
      });
      
and the result will be named organicResults.json

<img width="947" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/f73f2040-79d8-4788-b2cb-c530670c2ef1">

**Comment by charlesmana** [comment]
1. Import the fs module.
2. Create a new object to store the results.
3. Iterate over the organicResults array and add each object to the new object.
4. Convert the new object to a JSON string.
5. Write the JSON string to a file using the fs.writeFileSync() function.
6.  This function takes two arguments: the path to the file to write to and the data to write to the file. In this case, we are writing the JSON string to the file Scrapping-Tahu.json.
7.  you will have a JSON file named Scrapping-Tahu.json that contains the results of your
8. 
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/114788396/ee44e5f6-0602-416f-b1e6-d15f2b583c0c">
 search. You can then open this file in a text editor or use it in your application.

**Comment by IZAN0R** [comment]
1. import module "fs"
const fs = require('fs');

2. setelah fungsi "for", masukkan kode berikut
fs.writeFile('hasil.json', jsonData, (err) => {
if (err) throw err;
console.log('Data has been successfully added to the file');
});
});

![image](https://github.com/dudung/lecture-notes/assets/144424895/1e128958-9054-491e-a86c-f3956e6df33b)

**Comment by CriticalOlymp** [comment]
import module "fs"
const fs = require('fs');

setelah fungsi "for", masukkan kode berikut
fs.writeFile('hasil.json', jsonData, (err) => {
if (err) throw err;
console.log('Data has been successfully added to the file');
});
});

![Screenshot 2023-10-20 145856](https://github.com/dudung/lecture-notes/assets/144425203/aa403325-899d-435c-84de-57974c4aaa65)

**Comment by tegarhermans** [comment]
//import fs
const fs = require("fs");

//tambahkan syntax berikut di akhir sebelum getOrganicdata()
fs.writeFile("HasilScrapping.json", JSON.stringify(organicResults, null, 2), (err) => {
if (err) {
console.error("Error writing JSON file:", err);
} else {
console.log("JSON file saved successfully!");
}
});

![image](https://github.com/dudung/lecture-notes/assets/144425283/f5f6f584-7129-40ca-8d6e-ee0bb44e69d5)

**Comment by ayodyaadhi01** [comment]
Pertama, Import module "fs"
                  const fs = require('fs');
Kemudian, Masukkan kode berikut ini setelah fungsi "for"
                  const jsonData = JSON.stringify(organicResults);
                  fs.writeFileSync("JusManggaScraping.json", jsonData);
<img width="960" alt="Screenshot 2023-10-20 150303" src="https://github.com/dudung/lecture-notes/assets/144425145/681e8923-e003-4699-bc5d-cf3d4598a5e2">
<img width="960" alt="Screenshot 2023-10-20 150319" src="https://github.com/dudung/lecture-notes/assets/144425145/2232e127-08a1-4b42-874c-42cddb5ca3fd">

**Comment by birongzah** [comment]
const fs = require("fs");   
  // Save organic results to a JSON file
      const jsonData = JSON.stringify(organicResults, null, 2);
      fs.writeFileSync("organic_results.json", jsonData);
    });
};
<img width="800" alt="Screenshot 2023-10-20 at 15 03 58" src="https://github.com/dudung/lecture-notes/assets/144424494/daa0483a-c4ba-46d4-b39d-a9788a80b77b">

**Comment by yunoooo111** [comment]
import
const fs = require('fs');

fs.writeFile(
        "organicResultsgramedia.json",
        JSON.stringify(organicResults, null, 2),
        (err) => {
          if (err) {
            console.error("Error writing JSON file:", err);
          } else {
            console.log("JSON file saved successfully!");
          }
        }
      );
    });
};
![gramedjson](https://github.com/dudung/lecture-notes/assets/113901717/974a15db-8ff7-4329-b927-007fc3862372)

**Comment by yunoooo111** [comment]
import
const fs = require('fs');

fs.writeFile(
"organicResultsgramedia.json",
JSON.stringify(organicResults, null, 2),
(err) => {
if (err) {
console.error("Error writing JSON file:", err);
} else {
console.log("JSON file saved successfully!");
}
}
);
});
};

![gramedjson](https://github.com/dudung/lecture-notes/assets/113901717/853e0b91-fa4f-4eec-b391-d47820e1c26e)

**Comment by bahrudinz** [comment]
Masukan syntax -> const fs = require("fs");
untuk mengimport file system ke modul, kemudian tambahkan syntax berikut di akhir sebelum getOrganicdata()
fs.writeFile("organicResults.json", JSON.stringify(organicResults, null, 2), (err) => {
if (err) {
console.error("Error writing JSON file:", err);
} else {
console.log("JSON file saved successfully!");
}
});

hasilnya bernama organicResults.json
![image](https://github.com/dudung/lecture-notes/assets/144425269/bd99d9ae-8fe8-4450-8854-0cbc56eb4468)

**Comment by CyberianRonin** [comment]
Import the fs module.
Create a new object to store the results.
Iterate over the organicResults array and add each object to the new object.
Convert the new object to a JSON string.
Write the JSON string to a file using the fs.writeFileSync() function.
This function takes two arguments: the path to the file to write to and the data to write to the file. In this case, we are writing the JSON string to the file Scrapping-Ice.json.
you will have a JSON file named Scrapping-Ice.json 

![Screenshot (385)](https://github.com/dudung/lecture-notes/assets/122846418/10ff4e54-8691-429d-a688-5dfe42b92d4f)

**Comment by afrozhie** [comment]
import modul fs dengan
 ```md
const fs = require('fs');
```
lalu tambahkan fungsi untuk mengeksportnya dalam bentuk file json
```md
const jsonData = JSON.stringify(organicResults);
        fs.writeFileSync("scrapingGSERF.json", jsonData);
```
ini akan menghasilkan file bernama "scrapingGSERF.json"

![image](https://github.com/dudung/lecture-notes/assets/116063782/99cfc551-4539-4f60-9343-40f5347ff5d1)

**Comment by Ptolemu5** [comment]
Pertama, Import module "fs"
const fs = require('fs');
Kemudian, Masukkan kode berikut ini setelah fungsi "for"
const jsonData = JSON.stringify(organicResults);
fs.writeFileSync("JusManggaScraping.json", jsonData);
![Screenshot 2023-10-20 155746](https://github.com/dudung/lecture-notes/assets/144424941/cdd1855b-6b11-4cf5-b150-46f98169d318)

**Comment by Ptolemu5** [comment]
Pertama, Import module "fs"
const fs = require('fs');
Kemudian, Masukkan kode berikut ini setelah fungsi "for"
const jsonData = JSON.stringify(organicResults);
fs.writeFileSync("GoogleBooks
![Screenshot 2023-10-20 155746](https://github.com/dudung/lecture-notes/assets/144424941/3f72a2da-0072-4e9f-902c-ede76790985f)
.json", jsonData);

**Comment by yunisangadji** [comment]
const fs = memerlukan("fs");
// Simpan hasil organik ke file JSON
const jsonData = JSON.stringify(organicResults, null, 2);
fs.writeFileSync("organic_results.json", jsonData);
});
};
<img width="959" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/2ae28adf-2c70-4b0c-a1f1-df212404f6b1">

**Comment by ayarayenima** [comment]
import modul fs dengan
const fs = require('fs');
setelah itu tambahkan fungsi untuk mengeksportnya dalam bentuk file json
const jsonData = JSON.stringify(organicResults);
        fs.writeFileSync("chocolate.json", jsonData);
ini akan menghasilkan file bernama "chocolate.json"
![image](https://github.com/dudung/lecture-notes/assets/144424497/bce37359-97e3-4610-99a9-1210e87c3e27)

**Comment by Antara000** [comment]
```md
When you've done you're scraping, there's a few syntax you have to add :
1. you have to import module fs by adding : const fs = require("fs") //at line 3
2. for (let i = 0; i < titles.length; i++) {
        organicResults[i] = {
          title: titles[i],
          links: links[i],
          snippet: snippets[i],
          displayedLink: displayedLinks[i],
        };
      }

      // Convert the organicResults array to a JSON string
      const jsonData = JSON.stringify(organicResults, null, 2);

      // Write the JSON data to a file
      fs.writeFile("ScrapingGoogleGames.json", jsonData, (err) => {
        if (err) {
          console.error("Error writing JSON file:", err);
        } else {
          console.log("Organic results saved to organic_results.json");
        }
```
![image](https://github.com/dudung/lecture-notes/assets/144425065/00ddb049-ca76-4075-bdb1-d7a681895517)

**Comment by MazamGanendra** [comment]
import module "fs"
const fs = require('fs');

setelah fungsi "for", masukkan kode berikut
fs.writeFile('hasilscrapping.json', jsonData, (err) => {
if (err) throw err;
console.log('Data has been successfully added to the file');
});
});

![Screenshot 2023-11-03 145528](https://github.com/dudung/lecture-notes/assets/144425268/3b86cd19-96dd-4dfb-ace8-cb68164c6b44)
