### ISSUE TITLE
Medium story about how to scrap a Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#16]
Give the link to your Medium story.

**Comment by yunoooo111** [comment]
https://medium.com/@kadaptor/serp-scraping-with-node-js-b888a6e8cfb1

Yurnero Nolla
NIT: 21181296

**Comment by Antara000** [comment]
https://medium.com/@shakty209/serp-scraping-with-node-js-968d2788d19d

Makmur Perkasa
NIT:21181161

**Comment by afrozhie** [comment]
https://medium.com/@firemankampus/scraping-google-serp-with-node-js-e53187c32c8a

Firman Andrian
21181094

**Comment by CriticalOlymp** [comment]
https://medium.com/@cahyasatya14/a-programming-journey-fa709f1854f7

Chandra Martadinata
21181064

**Comment by charlesmana** [comment]
https://medium.com/@citayogiprtm6/serp-scrapping-with-node-js-cd59770a66e5?postPublishedType=initial

Charnadi Lesmana
21181068

**Comment by c4t4r** [comment]
https://medium.com/@dimanalfon/serp-scraping-with-node-js-4ec406a53e27

Diman Alfon
211181074

**Comment by Ptolemu5** [comment]
https://medium.com/@murrobifath1/belajar-melakukan-scraping-google-ed20fc7ed709

Murrobi Fatahillah
21181203

**Comment by Ptolemu5** [comment]
https://medium.com/@murrobifath1/belajar-melakukan-scraping-google-ed20fc7ed709

Murrobi Fatahillah
21181203

**Comment by yunisangadji** [comment]
https://medium.com/@yuniasangadji/apa-itu-web-sraping-fd48f4a6c876

Yulia Valonia
21181298

**Comment by dudung** [comment]
> https://medium.com/@yuniasangadji/apa-itu-web-sraping-fd48f4a6c876
> 
> Yulia Valonia 21181298

Please submit to issues of the new repo https://github.com/dudung/web-app-service-tasks/issues

**Comment by AKS4R4** [comment]
https://medium.com/@raihanmarlianto/pengalaman-mempelajari-dan-melakukan-scraping-google-66ebdb2c0bc5
![image](https://github.com/dudung/lecture-notes/assets/144425016/45c0c06f-df48-46a9-ba88-026eb422128d)
