### ISSUE TITLE
Advance Google Search

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#17]
Show how to find a definition about something in a particular website between 2000 and 2010.
+ Put the link here.
+ Show the results in the form of screenshots.

**Comment by c4t4r** [comment]
https://www.google.com/search?q=define%3Apresiden+site%3Ahttps://id.wikipedia.org/+after%3A2000+before%3A2010
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/122764330/fe53f98f-1e06-44df-9aeb-0c7c4e920667">

**Comment by IZAN0R** [comment]
https://www.google.com/search?q=define%3ADPR+site%3A+https%3A%2F%2Fwww.acronymfinder.com%2FDPR.html+after%3A2000+before%3A2010

![image](https://github.com/dudung/lecture-notes/assets/144424895/29d11f71-a7cf-4d51-bde0-298e9a37acaf)

**Comment by IZAN0R** [comment]
https://www.google.com/search?q=define%3ADPR+site%3A+https%3A%2F%2Fwww.acronymfinder.com+after%3A2000+before%3A2010

![image](https://github.com/dudung/lecture-notes/assets/144424895/f7763497-4ffa-448c-9139-d32e25eba8d8)

**Comment by NerdyVandheka** [comment]
https://www.google.com/search?q=define%3Adeath+metal+site%3Ahttps%3A%2F%2Fwww.deathmetal.org%2F+after%3A2000+before%3A2010&sca_esv=575117049&rlz=1C1UEAD_enID997ID997&sxsrf=AM9HkKmbWmyP3_Yn9s6oYYxhtjyRk3yP2Q%3A1697789302468&ei=djUyZY2SHJGZseMPrKa40Aw&ved=0ahUKEwiNpZuCloSCAxWRTGwGHSwTDsoQ4dUDCBE&uact=5&oq=define%3Adeath+metal+site%3Ahttps%3A%2F%2Fwww.deathmetal.org%2F+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiSmRlZmluZTpkZWF0aCBtZXRhbCBzaXRlOmh0dHBzOi8vd3d3LmRlYXRobWV0YWwub3JnLyBhZnRlcjoyMDAwIGJlZm9yZToyMDEwSABQAFgAcAB4AJABAJgBAKABAKoBALgBA8gBAPgBAvgBAeIDBBgAIEE&sclient=gws-wiz-serp
![Screenshot 2023-10-20 151007](https://github.com/dudung/lecture-notes/assets/144425376/9d9d33a3-1529-4174-85fd-74992b6131a4)

**Comment by CriticalOlymp** [comment]
https://www.google.com/search?q=define%3Akopi+site%3Atokopedia.com+2000..2010&sca_esv=575056345&sxsrf=AM9HkKmIDRf5Vs9TtfpfYrqI_BmIVzgOVw%3A1697786801661&ei=sSsyZfHYJ_yE4-EP05ODmAw&ved=0ahUKEwix9d3ZjISCAxV8wjgGHdPJAMMQ4dUDCBE&uact=5&oq=define%3Akopi+site%3Atokopedia.com+2000..2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiKWRlZmluZTprb3BpIHNpdGU6dG9rb3BlZGlhLmNvbSAyMDAwLi4yMDEwSK6HCFDDC1ir-wVwF3gBkAEDmAG3A6ABqS-qAQg2OS44LjQtMbgBA8gBAPgBAfgBAqgCE8ICChAAGEcY1gQYsAPCAgoQABiKBRiwAxhDwgIOEAAY5AIY1gQYsAPYAQHCAhAQLhiKBRjIAxiwAxhD2AECwgILEC4YgwEYsQMYgATCAgUQABiABMICBxAuGIoFGEPCAhoQLhiDARixAxiABBiXBRjcBBjeBBjgBNgBA8ICBxAjGOoCGCfCAhAQABiKBRjqAhi0AhhD2AEEwgITEC4YigUYyAMY6gIYtAIYQ9gBAsICFhAAGAMYjwEY5QIY6gIYtAIYjAPYAQXiAwQYACBBiAYBkAYTugYGCAEQARgJugYGCAIQARgIugYGCAMQARgUugYGCAQQARgBugYGCAUQARgL&sclient=gws-wiz-serp#ip=1
![Screenshot 2023-10-20 151011](https://github.com/dudung/lecture-notes/assets/144425203/b68eb3cd-a33a-413d-8707-7df954b90152)

**Comment by tegarhermans** [comment]
https://www.google.com/search?q=define%3Abank+indonesia+site%3Awikipedia.org+after%3A2000+before%3A2010&sca_esv=575117049&sxsrf=AM9HkKmBzphWyqAy85SpRYHrZUdg-nJuAg%3A1697789855534&ei=nzcyZeSPIION4-EPisK-yA4&ved=0ahUKEwik2_eJmISCAxWDxjgGHQqhD-kQ4dUDCBA&uact=5&oq=define%3Abank+indonesia+site%3Awikipedia.org+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiP2RlZmluZTpiYW5rIGluZG9uZXNpYSBzaXRlOndpa2lwZWRpYS5vcmcgYWZ0ZXI6MjAwMCBiZWZvcmU6MjAxMEjBTFAAWJdKcAB4AJABAJgBPqABeKoBATK4AQPIAQD4AQHiAwQYACBBiAYB&sclient=gws-wiz-serp
![image](https://github.com/dudung/lecture-notes/assets/144425283/7fd45f71-3026-4b1c-8d3f-a4a354d88c68)

**Comment by yunoooo111** [comment]
https://www.google.com/search?q=define%3A+megawati+site%3A+https%3A%2F%2Fid.wikipedia.org%2F+after%3A2000+before%3A2010&sca_esv=575127353&sxsrf=AM9HkKnFr2YKrx-nw7nd0ObYqBioSTGlmQ%3A1697789995808&ei=KzgyZY7-MLWs4-EPlemBkAI&ved=0ahUKEwjOv-nMmISCAxU11jgGHZV0ACIQ4dUDCBE&uact=5&oq=define%3A+megawati+site%3A+https%3A%2F%2Fid.wikipedia.org%2F+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiR2RlZmluZTogbWVnYXdhdGkgc2l0ZTogaHR0cHM6Ly9pZC53aWtpcGVkaWEub3JnLyBhZnRlcjoyMDAwIGJlZm9yZToyMDEwSABQAFgAcAB4AJABAJgBAKABAKoBALgBA8gBAPgBAvgBAeIDBBgAIEE&sclient=gws-wiz-serp

![advancinggooglescrape](https://github.com/dudung/lecture-notes/assets/113901717/7075db0c-581a-4efa-97e7-8a9196e3f079)

**Comment by Antara000** [comment]
https://www.google.com/search?client=opera-gx&q=define%3Abenua+after%3A2000+before%3A2010&sourceid=opera&ie=UTF-8&oe=UTF-8
![image](https://github.com/dudung/lecture-notes/assets/144425065/b88b7e3f-3f33-41ef-a652-dbd739d76db9)

**Comment by afrozhie** [comment]
https://www.google.com/search?q="monitor"+site%3Ashopee.co.id+after%3A2000+before%3A2010

![image](https://github.com/dudung/lecture-notes/assets/116063782/da3daaf8-db6e-4061-8dd4-4edd8778e8cc)

**Comment by bahrudinz** [comment]
https://www.google.com/search?client=opera-gx&q=define+%3A+presiden+site%3A+www.liputan6.com+after%3A2000+before%3A2010&sourceid=opera&ie=UTF-8&oe=UTF-8
![image](https://github.com/dudung/lecture-notes/assets/144425269/aaddf654-940f-4a20-9a7a-32feb576d4a7)

**Comment by ayodyaadhi01** [comment]
https://www.bing.com/search?q=define%3Ajusmangga+site%3Ahttps%3A%2F%2Fwww.halodoc.com%2Fartikel%2F+after%3A2000+before%3A2010&qs=n&form=QBRE&sp=-1&lq=1&pq=define%3Ajusmangga+site%3Ahttps%3A%2F%2Fwww.halodoc.com%2Fartikel%2F+after%3A2000+before%3A2010&sc=0-77&sk=&cvid=A7FECDE147B3415A8822C4F9A82BC9C2&ghsh=0&ghacc=0&ghpl=
<img width="960" alt="Screenshot 2023-10-20 154623" src="https://github.com/dudung/lecture-notes/assets/144425145/aa4073b6-374b-4374-8d74-7042fc1fd1cb">
<img width="960" alt="Screenshot 2023-10-20 154641" src="https://github.com/dudung/lecture-notes/assets/144425145/11e79ea5-279a-4423-aeef-41f22a05a314">

**Comment by NeganSmith92** [comment]
https://www.google.com/search?q=define%3Amovies+site%3Ahttps%3A%2F%2Fwww.imdb.com%2F+after%3A2000+before%3A2010&sca_esv=575127353&sxsrf=AM9HkKku3FUyZjy7xfI_h3M3Zgcxtyu8eA%3A1697792352194&source=hp&ei=YEEyZdCaCbys4-EP1cKu4AI&iflsig=AO6bgOgAAAAAZTJPcOiRXf_-Hky7WpOXgRKnlb60wGus&ved=0ahUKEwjQyrWwoYSCAxU81jgGHVWhCywQ4dUDCAs&uact=5&oq=define%3Amovies+site%3Ahttps%3A%2F%2Fwww.imdb.com%2F+after%3A2000+before%3A2010&gs_lp=Egdnd3Mtd2l6Ij9kZWZpbmU6bW92aWVzIHNpdGU6aHR0cHM6Ly93d3cuaW1kYi5jb20vIGFmdGVyOjIwMDAgYmVmb3JlOjIwMTBI7cwIUJQQWLq9CHADeACQAQCYAYkDoAGGKaoBCTQxLjEyLjEuMbgBA8gBAPgBAfgBAqgCCsICBxAjGOoCGCfCAgcQIxiKBRgnwgIEECMYJ8ICCBAAGIAEGLEDwgILEC4YigUYsQMYgwHCAgsQABiKBRixAxiDAcICERAuGIAEGLEDGIMBGMcBGNEDwgINEAAYigUYsQMYgwEYCsICBRAAGIAEwgILEAAYgAQYsQMYgwHCAhAQABiKBRixAxiDARhGGPkBwgIIEAAYywEYgATCAgoQABjLARiABBgKwgINEAAYywEYgAQYRhj5AcICBhAAGBYYHsICCBAAGBYYHhgPwgIIEAAYFhgeGArCAgcQIRigARgKwgIFECEYoAHCAgUQABiiBA&sclient=gws-wiz#ip=1


<img width="464" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/c9290506-f80b-4d28-aef1-1f57393254a6">

**Comment by yunisangadji** [comment]
https://www.google.com/search?q=define%3APapeda+site%3A+https%3A%2F%2Fid.wikipedia.org%2Fwiki%2FPapeda+after%3A2000+before%3A2010&sca_esv=575108319&sxsrf=AM9HkKlCbEIu1zDVktuVFZfIAXp6u9gc0w%3A1697786862350&ei=7isyZaiGFfmu4-EP0YS6yAc&ved=0ahUKEwiotdb2jISCAxV51zgGHVGCDnkQ4dUDCBE&uact=5&oq=define%3APapeda+site%3A+https%3A%2F%2Fid.wikipedia.org%2Fwiki%2FPapeda+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiT2RlZmluZTpQYXBlZGEgc2l0ZTogaHR0cHM6Ly9pZC53aWtpcGVkaWEub3JnL3dpa2kvUGFwZWRhIGFmdGVyOjIwMDAgYmVmb3JlOjIwMTBI_LAGUJYFWOqmBnAKeAGQAQOYAdADoAGFFaoBCDIzLjUuNC0xuAEDyAEA-AEB-AECqAIRwgIKEAAYRxjWBBiwA8ICChAAGIoFGLADGEPCAg4QABjkAhjWBBiwA9gBAcICEBAuGIoFGMgDGLADGEPYAQLCAgcQIxiKBRgnwgINEC4YgwEYsQMYigUYQ8ICBBAAGAPCAgUQABiABMICCxAAGIAEGLEDGIMBwgIcEC4YgwEYsQMYigUYQxiXBRjcBBjeBBjfBNgBA8ICBxAjGOoCGCfCAhMQLhiKBRjIAxjqAhi0AhhD2AEC4gMEGAAgQYgGAZAGE7oGBggBEAEYCboGBggCEAEYCLoGBggDEAEYFA&sclient=gws-wiz-serp
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/69393764-cb42-4e67-9271-f4f82fe23b17">

**Comment by MazamGanendra** [comment]
https://www.google.com/search?q=define+%3A+minuman+dingin+site%3A+quora+after%3A2000+before%3A2010&client=opera-gx&hs=KRt&sca_esv=579077719&sxsrf=AM9HkKn-w3RI7A7kI-SbzPcSpyrPE2qCCA%3A1698998441504&ei=qahEZYS3Hp-c4-EPvsuwiAU&ved=0ahUKEwjEr9G0rqeCAxUfzjgGHb4lDFEQ4dUDCA8&uact=5&oq=define+%3A+minuman+dingin+site%3A+quora+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiOmRlZmluZSA6IG1pbnVtYW4gZGluZ2luIHNpdGU6IHF1b3JhIGFmdGVyOjIwMDAgYmVmb3JlOjIwMTBInxBQ8QFYzghwAXgAkAEAmAFDoAHVAaoBATS4AQPIAQD4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp
![Screenshot 2023-11-03 150053](https://github.com/dudung/lecture-notes/assets/144425268/ca53f8fe-c985-48ff-a7e4-673fabcb5128)

**Comment by Ptolemu5** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424941/36331eab-d2bf-4a6d-8b6a-6cdb8aa700b0)

**Comment by Ptolemu5** [comment]
https://www.google.com/search?client=opera-gx&q=googlebook&sourceid=opera&ie=UTF-8&oe=UTF-8
![image](https://github.com/dudung/lecture-notes/assets/144424941/7fcdc609-f21b-4401-94a4-5b9fcf315050)

**Comment by charlesmana** [comment]
https://www.google.com/search?q=define%3A+KPK+site%3A+https%3A%2F%2Fwww.kompas.com+after%3A+2010+before%3A+2023&sca_esv=583337381&sxsrf=AM9HkKkqst9f0ua8hZgunmYkvcbRKxxfxQ%3A1700225366607&source=hp&ei=VmFXZbe5Is-K-Qbh_ZegBw&iflsig=AO6bgOgAAAAAZVdvZhso3Vd4PndIFhvhjzAYg9-jFGEL&ved=0ahUKEwi3vIyIicuCAxVPRd4KHeH-BXQQ4dUDCAo&uact=5&oq=define%3A+KPK+site%3A+https%3A%2F%2Fwww.kompas.com+after%3A+2010+before%3A+2023&gs_lp=Egdnd3Mtd2l6IkFkZWZpbmU6IEtQSyBzaXRlOiBodHRwczovL3d3dy5rb21wYXMuY29tIGFmdGVyOiAyMDEwIGJlZm9yZTogMjAyM0j71aEBUNf9mgFYg8KhAXAMeACQAQWYAfEIoAHYzAGqARIwLjEzLjE1LjEyLjcuMy45LjS4AQPIAQD4AQGoAgrCAgoQIxiABBiKBRgnwgIOEAAYgAQYigUYsQMYgwHCAggQLhiABBixA8ICBRAAGIAEwgIIEAAYgAQYsQPCAgsQABiABBixAxiDAcICBRAuGIAEwgIHECMY6gIYJ8ICBBAjGCfCAhAQABiABBiKBRixAxiDARgKwgIHECMYigUYJ8ICBxAAGIAEGAo&sclient=gws-wiz
![Uploading Screenshot 2023-11-17 203536.png…]()

**Comment by AKS4R4** [comment]
https://www.google.com/search?q=define+%3A+baju+site+%3A+https%3A%2F%2Ftokopedia.com&sca_esv=601288450&sxsrf=ACQVn0-PQ8rAqqK-HNZR-d0RgtYByN1iiA%3A1706150837964&ei=tcuxZcu4Ov6-4-EPzp-J-Ac&ved=0ahUKEwiL54SVw_eDAxV-3zgGHc5PAn8Q4dUDCBA&uact=5&oq=define+%3A+baju+site+%3A+https%3A%2F%2Ftokopedia.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKmRlZmluZSA6IGJhanUgc2l0ZSA6IGh0dHBzOi8vdG9rb3BlZGlhLmNvbTIFECEYoAEyBRAhGKABSPh-UJQLWLBvcAl4AZABAJgBxwOgAZUwqgEKMC4yOC4yLjMuMrgBA8gBAPgBAcICChAAGEcY1gQYsAPCAggQABgWGB4YD8ICBhAAGBYYHsICCBAAGBYYHhgKwgILEAAYgAQYigUYhgPCAggQABiABBiiBMICBRAhGJ8FwgIHECEYChigAeIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp
![Screenshot 2024-01-25 094747](https://github.com/dudung/lecture-notes/assets/144425016/0132a0c8-f341-4846-96a2-3fcfe410c4b0)
