### ISSUE TITLE
Node.js for Google Scholar SERP

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#18]
Write here
+ your NIM
+ Link to you Medium story

For example
```
+ 10223007
+ https://medium.com/@6unpnp/node-js-for-google-scholar-ddd80baaebxx
```
will produce
+ 10223007
+ https://medium.com/@6unpnp/node-js-for-google-scholar-ddd80baaebxx

**Comment by yusuff10** [comment]
- 10220021
- https://medium.com/@yusuf_f10/web-scraping-dengan-node-js-menggunakan-unirest-dan-cheerio-89123953eaa8

**Comment by desulight99** [comment]
- 10220082
- https://medium.com/@desulight99/cara-scrape-data-dari-google-scholar-gs-dengan-node-js-6d9daeddd784

**Comment by MaynardoPS** [comment]
+ 10220063
+ https://medium.com/@maynardosoegianto/scraping-data-memanfaatkan-node-js-yay-or-nay-7f9e121f6055

**Comment by MalikAnshari-048** [comment]
- 10220048
- https://medium.com/@malik.el.anshary/scraping-on-google-scholar-34de60674e9f

**Comment by gitaameliiaa** [comment]
- 10220018
- https://medium.com/@gitaameliamarianto26/scraping-google-scholar-using-node-js-9b74eb52a90c

**Comment by BernardSujono** [comment]
10220011
https://medium.com/@bernardsujono10/how-to-scraping-google-scholar-with-node-js-bbc6a4fd8484

**Comment by BernardSujono** [comment]
- 10220011
- https://medium.com/@bernardsujono10/how-to-scraping-google-scholar-with-node-js-bbc6a4fd8484

**Comment by clarissastvn** [comment]
+ 10220042
+ https://medium.com/@clarissastvn/scraping-data-dengan-node-js-c6630c7bf8cf

**Comment by elsbthbunga** [comment]
- 10220068
- https://medium.com/@elsbthbunga/how-to-web-scrapping-dari-google-scholar-dengan-node-js-bbccb82e66d4

**Comment by cyukis** [comment]
+ 10220056
+ https://medium.com/@cyukis/scraping-hasil-pencarian-google-scholar-a976a1977d68

**Comment by saaniyara** [comment]
- 10220076
- https://medium.com/@tsaniyahhz/mengenal-node-js-scrape-google-scholar-gs-9aa9dd591dba

**Comment by dianatan** [comment]
- 10220038
- https://medium.com/@dtanoto88/scraping-google-scholar-dengan-node-js-970596637297

**Comment by RizkiArdikaF** [comment]
- 10219023
- https://medium.com/@rizki.ardika.f/google-scholar-data-scraping-and-node-js-shenanigan-0f33562a1a7e

**Comment by kaniedo25** [comment]
- 10219009
- https://medium.com/@kaniedo/pusing-dengan-hasil-google-scholar-tenang-scraping-in-saja-517d47ab28d5

**Comment by emahdyt** [comment]
- 10220051
- https://medium.com/@ermas.hidayati/first-step-to-scraping-in-google-scholar-54de0dbb07d6

**Comment by Sarahaul** [comment]
+ 10220080
+ https://medium.com/@sarahauliyaurrohman52/scraping-data-menggunakan-node-js-337e768369d3

**Comment by NurlailaTan** [comment]
- 10219076
- https://medium.com/@nurlailahtan/melakukan-scraping-di-google-scholar-dengan-node-js-e8f08da0ab53

**Comment by syakuradhya** [comment]
- 10220073
- https://syakuradhya.medium.com/node-js-for-scraping-google-serp-b66a874b09e3

**Comment by purwariadi** [comment]
- 10219109
- https://medium.com/@purwasatria/node-js-to-the-rescue-3e7c48c75ba

**Comment by yuliajanah** [comment]
+ 101219075
+ https://medium.com/@yuliajanah041/srcaping-google-schoolar-dengan-node-js-6a5f9b583ae0

**Comment by ElizabethMichele** [comment]
**_- 10220004_**
- https://medium.com/@elizabeth.michelee/scrapping-google-scholar-dengan-node-js-c818b1ffc5e2

**Comment by fatihahjazaaufa** [comment]
- 10220013
- https://medium.com/@fatihahjaza/scraping-google-scholar-dengan-node-js-087e44fd6013

**Comment by ArkanantaR** [comment]
- 10220014
- https://arkanantaltmpt.medium.com/chapter-4-when-you-are-lazy-enough-to-cite-the-prerequisite-test-ad233dbcb1a1

**Comment by rafifprastya** [comment]
+ 10220033
+ https://medium.com/@rafifprastya/0755e3038cc3

**Comment by Voxxis11** [comment]
- 10220035
- https://medium.com/@aldiarbie/pemanfaatan-node-js-untuk-scraping-data-google-scholar-10e33f6590ee

**Comment by DedeAditiaaa** [comment]
- 10220007
- https://medium.com/@dedeaditiaa/scraping-google-menggunakan-node-js-966779f1730b

**Comment by azkabudiman21** [comment]
- 10219056
- https://medium.com/@azkabudiman/scraping-google-scholar-using-node-js-e87bb2b3dd63

**Comment by keziaalodiac** [comment]
- 10220009
- https://medium.com/@keziaalodiac/web-scraping-collecting-research-data-from-google-scholar-db7954bc3985

**Comment by andrewanggoh** [comment]
+ 10220012
+ https://medium.com/@andrew.anggoh/scraping-google-scholar-with-javascript-34969ca72078

**Comment by BerlianOkaI** [comment]
- 10220037
- https://medium.com/@varhitera21/scraping-google-scholar-with-node-js-8759b681785c

**Comment by BracchialisG** [comment]
- 10220067
- https://rekryanta.medium.com/scraping-google-scholar-dengan-node-js-cara-mendapatkan-daftar-jurnal-dan-abstrak-49e1fa7fef0c
