### ISSUE TITLE
Safety by design challenges

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#24]
+ Read the story https://medium.com/@6unpnp/safety-by-design-an-intro-856eef425724
+ Accept the challenges at the end of the story
+ Write here and also in the comment of the story
  - Your NIM
  - Link to your story

Attachment [safety-by-design.xlsx](https://github.com/dudung/lecture-notes/files/13303480/safety-by-design.xlsx) (if necessary)

**Comment by aszmukhsin** [comment]
Here is my reply to the story, hope can give other point of view about reactor evolution by safety design

[https://medium.com/@aszmukhsin/next-nuclear-reactor-generation-evolution-by-safety-design-5b777448a2ae](https://github.com/@aszmukhsin/next-nuclear-reactor-generation-evolution-by-safety-design-5b777448a2ae?source=responses-----856eef425724---------------------respond_sidebar-----------)

Muksin Aji S_24922003

**Comment by airinehijrah** [comment]
Airine Hijrah Handayani_24922004
https://medium.com/@airinesaputro/pressurized-water-reactors-pwrs-and-high-temperature-gas-cooled-reactors-htgrs-from-different-f48b560a42b3
