### ISSUE TITLE
FEM analysis Hands-on in Python using anaStruct

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#25]
+ Read the story [A very simple example of FEM analysis for structure with Python: Following a working tutorial](https://medium.com/@6unpnp/a-very-simple-example-of-fem-analysis-for-structure-with-python-3178fa5997e4)
+ Accept the given challenges therein.
+ Report also link of your response, in the form of a Medium story, here.

**Comment by tsaniyahhz** [comment]
10

**Comment by tsaniyahhz** [comment]
dsada

**Comment by Sarahaul** [comment]
The article "[A very simple example of FEM analysis for structure with Python: Following a working tutorial](https://medium.com/@6unpnp/a-very-simple-example-of-fem-analysis-for-structure-with-python-3178fa5997e4)" has very insightful information. Thank you Sir, so i try to use Phyton for analysist structure. This is link for my article,
https://medium.com/@sarahauliyaurrohman52/struktur-dalam-spsf-ffabf02f1f10

**Comment by gitaameliiaa** [comment]
Your article is very insightful and interesting, Sir! Thank you very much for always making nice articles that i can read and increase my knowledge. I tried to use anastruct on my own structure, i tried to make a simple bridge structure. Here's my article https://medium.com/@gitaameliamarianto26/analisis-struktur-menggunakan-finite-element-method-0707c1434522

**Comment by kaniedo25** [comment]
Thanks for your article about this FEM, Sir. It's helpfully for my next study.

anyway, here my medium which answer the challenges from Mr. 6npnp:

[https://medium.com/@kaniedo/python-pemecah-masalah-finite-element-method-fem-dc1b6e654eaa](url)

**Comment by syakuradhya** [comment]
Thank you, sir for sharing this insightful article. This is very useful and interesting information for me, so I know that structural analysis can be done by using a Python. I tried to analyzed a bridge structure using steps from this article, and here is my article about that.
https://syakuradhya.medium.com/fem-untuk-analisis-struktur-dengan-anastruct-pada-python-bb699feb2b71

**Comment by NurlailaTan** [comment]
Thank you, Sir, for writing this article. I have observed the challenges in your article and attempted them. Here are the results I have, with a different simple structure. 
https://medium.com/@nurlailahtan/analisis-struktur-menggunakan-anastruct-1b56a5e4f379

**Comment by andrewanggoh** [comment]
Thank you for sharing this article, Sir! It's very interesting and insightful for me. I tried to make an article to complete the challenges. Here is the link to my article:

https://medium.com/@andrew.anggoh/analisis-strucktur-menggunakan-anastruct-59b2c09d5da8

**Comment by dianatan** [comment]
Thank you sir for sharing this interesting article, it is very insightful for me. I tried to analyze a different structure and here is the result.
https://medium.com/@dtanoto88/f-e-m-untuk-analisis-struktur-f93c9ba7f4ed

**Comment by ElizabethMichele** [comment]
Thank you for the insightful article, "A Very Simple Example of FEM Analysis for Structure with Python: Following a Working Tutorial." Inspired by your work, I utilized anastruct for my own structure, and here's the link to my article https://medium.com/@elizabeth.michelee/analisis-struktur-dengan-finite-elemet-methode-menggunakan-library-anastruct-pada-python-291173b6e88e. Much appreciated!

**Comment by fatihahjazaaufa** [comment]
Great article! It is easy to follow and concise. Here is my article about using anaStruct
https://medium.com/@fatihahjaza/analisis-struktur-menggunakan-anastruct-ee6cd9e65459

**Comment by BracchialisG** [comment]
Thanks a bunch for this well-written piece! Your step-by-step guide really helped me understand the intricacies of FEM analysis with Python. The anaStruct library is indeed powerful, and your article made it accessible. Kudos! Here is my article about similar topic https://rekryanta.medium.com/struktur-spsf-909e419102df

**Comment by emahdyt** [comment]
Thanks for your insight article Sir. This is my simple structure, analyze with anaStruct
https://medium.com/@ermas.hidayati/anastruct-sebagai-analisis-struktur-a2c255ff94b8
Thank you, and I am really sorry because for the late submit.
