### ISSUE TITLE
Idea for a website and the result

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#4]
Total point = 100
+ Describe you idea in one paragraph in Indonesian language less than 100 words (Point 20)
+ Link to the website (Point 10)
+ Create a Hugo static website containing following components
  - LaTeX (Point 5)
  - Mermaid (Point 5)
  - ChartJS (Point 5)
  - Markdown for table (Point 5)
  - Markdown for YouTube video (Point 5)
  - Markdown for quote paragraph (Point 5)
  - Markdown for section and subsection (Point 5)
  - Markdown for external image (Point 5)
  - Markdown for link to external page (Point 5)
  - Pure HTML / JS / CSS (Point 5)
  - SVG image with animation (Point 10)
+ Website has integrated meaning (Point 10)

**Comment by afrozhie** [comment]
Firman Andrian
21181094

Saya akan membuat sebuah one page website kursus online, dimana didalamnya terdapat materi materi yang telah di upload oleh para pengajar, jadwal kursus, dan sebagainya.
Link : https://afrozhie.github.io/lecture-notes/AyoBelajar/

**Comment by yunoooo111** [comment]
Nama : Yurnero Nolla
NIT : 21181296
Saya membuat website sederhana tentang sebuah music store yang menjual produk-produk berkualitas 
https://yunoooo111.github.io/lecture-notes/0049/#order

**Comment by NerdyVandheka** [comment]
Nama : Nerdy Vandheka
NIT : 21181213
Saya membuat sebuah website yang berisi tentang hidup saya sendiri. Dimana website ini membahas asal usul saya hingga rutinitas saya sehari - hari. 
https://nerdyvandheka.github.io/lecture-notes/0048/

**Comment by CriticalOlymp** [comment]
Nama : Chandra Martadinata
NIT : 21181064
Web berisikan tentang tips belajar trigonometri
https://criticalolymp.github.io/lecture-notes/0048/

**Comment by narapatimulia** [comment]
Name : Mulia Narapati
NIT : 21181195

Page mengenai Pendaftaran Taruna/i AKMIL t.a. 2025/2026

https://narapatimulia.github.io/lecture-notes/0049/

**Comment by IZAN0R** [comment]
Nama : Diego Pradipta
NIT : 21181085

Web berisikan tentang Akademi Kepolisian

https://izan0r.github.io/lecture-notes/0048/

**Comment by Antara000** [comment]
Nama : Makmur Perkasa
NIT : 21181161

Page ini mengenai cara mendapatkan sertifikasi diving dengan plan serta tahapan yang ada
https://antara000.github.io/lecture-notes/ScubaDivingCourse/

**Comment by NeganSmith92** [comment]
Nama : Zafran Marvis
NIT : 21181300

Saya membuat Website tentang penjelasan Geometri
url : https://negansmith92.github.io/lecture-notes/0048/

**Comment by IZAN0R** [comment]
Nama : Diego Pradipta
NIT : 21181085

Saya membuat website tentang AKPOL
url : https://izan0r.github.io/lecture-notes/0048/

**Comment by c4t4r** [comment]
Nama : Diman Alfon
NIT : 21181074

Saya membuat website tentang STIN
url : https://c4t4r.github.io/lecture-notes/0048/

**Comment by bahrudinz** [comment]
Nama : Mudzafar Azzam
NIT : 21181177


link : https://bahrudinz.github.io/lecture-notes/0050/
deskripsi : Saya membuat website tentang penjelasan bagaimana menajga badan ideal dengan menjelaskan kriteria badan yang kurus ideal dan gemuk melalui pola makan 4 sehat 5 sempurna dan olahraga teratur

**Comment by MazamGanendra** [comment]
Nama : Mazam Ganendra
NIT : 21181192

Saya membuat website mengenai pengenalan virus pemeras yang sangat berbahaya pada masanya, yaitu virus WannaCry            ( Ransomware )
link : https://mazamganendra.github.io/lecture-notes/0048/

**Comment by ayodyaadhi01** [comment]
Nama : Ayodya Adhi
NIT : 21181017

Saya membuat website tentang LSM Kasih Sayang Anak yang menggagas gerakan peduli anak
URL : https://ayodyaadhi01.github.io/lecture-notes/pedulianak/

**Comment by CyberianRonin** [comment]
Nama : Resna Febrianto
NIT : 21181229

Saya membuat website tentang Food Blog
URL : https://cyberianronin.github.io/lecture-notes/0048/

**Comment by charlesmana** [comment]
NAMA : Charnadi Lesmana
NIT :21181068

Website mengenai STIN dan Pendaftaran Taruna Baru
URL : https://charlesmana.github.io/lecture-notes/0048/

**Comment by ayarayenima** [comment]
NAMA : Ayara Yenima
NIT : 21181032

Website Mengenai Penggunaan Kendaraan Pribadi dan Transportasi Umum
URL : https://ayarayenima.github.io/lecture-notes/0048/

**Comment by tegarhermans** [comment]
NAMA : Tegar Herman S
NIT : 21181284

website usaha barbershop
URL : https://tegarhermans.github.io/lecture-notes/sergeant

**Comment by Ptolemu5** [comment]
Nama : Murrobi Fatahillah
NIT  : 21181203

website pusat informasi dan pengolahan data
https://ptolemu5.github.io/lecture-notes/0048/
