### ISSUE TITLE
Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#6]
Report a Google SERP from you search by writing
+ your Medium link, e.g. https://medium.com/@6unpnp
+ your GitHub profile page, e.g. https://github.com/dudung
+ your Google SERP, e.g. https://www.google.com/search?q=something

**Comment by Antara000** [comment]
https://medium.com/@shakty209
https://github.com/Antara000
https://www.google.com/search?q=google+games

**Comment by ayarayenima** [comment]
https://medium.com/@ayarayenima
https://github.com/ayarayenima
https://www.google.com/search?q=Chocolate

**Comment by CriticalOlymp** [comment]
https://medium.com/@cahyasatya14
https://github.com/CriticalOlymp
https://www.google.com/search?q=kopi+arabika

**Comment by narapatimulia** [comment]
https://medium.com/@patinarapati 
https://github.com/narapatimulia
https://www.google.com/search?q=indomie

**Comment by bahrudinz** [comment]
https://medium.com/@bahrudinnafa01
https://github.com/bahrudinz
https://www.google.com/search?q=sabotase

**Comment by afrozhie** [comment]
Firman Andrian
21181094

https://medium.com/@firemankampus
https://github.com/afrozhie
https://www.google.com/search?q=pemuda+jihad

**Comment by CyberianRonin** [comment]
https://medium.com/@febriantoresna
https://github.com/CyberianRonin
https://www.google.com/search?q=ice+cream

**Comment by Ptolemu5** [comment]
https://medium.com/@ptolemu5
https://github.com/ptolemu5
https://www.google.com/search?q=google+book

**Comment by NeganSmith92** [comment]
https://medium.com/@zfadhlurramadhan2911
https://github.com/NeganSmith92
https://www.google.com/search?q=sports

**Comment by IZAN0R** [comment]
https://medium.com/@yayawsutaryaw
https://github.com/IZAN0R
https://www.google.com/search?q/DPR

**Comment by birongzah** [comment]
https://medium.com/@reinaldoulian
https://github.com/birongzah
https://www.google.com/search?q=bakso&bshm=rime/1

**Comment by NerdyVandheka** [comment]
https://medium.com/@crewsakan1312
https://github.com/NerdyVandheka
https://www.google.com/search?q=death+metal

**Comment by ayodyaadhi01** [comment]
https://medium.com/@yoday5852
https://github.com/ayodyaadhi01
https://www.google.com/search?q=jus+mangga

**Comment by tegarhermans** [comment]
https://medium.com/@saputrotegar.st
https://github.com/tegarhermans
https://www.google.com/search?q=chairul+tanjung

**Comment by charlesmana** [comment]
https://medium.com/@citayogiprtm6
https://github.com/charlesmana
https://www.google.com/search?q=tahu

**Comment by yunoooo111** [comment]
https://github.com/yunoooo111
https://medium.com/@kadaptor
https://www.google.com/search?q=gramedia

**Comment by MazamGanendra** [comment]
https://github.com/MazamGanendra
https://medium.com/@masjhurhusein
https://www.google.com/search?q=minuman+dingin

**Comment by irhwam** [comment]
https://github.com/irhwam
https://medium.com/@prajawigoona
https://www.google.com/search?q=bogor

**Comment by c4t4r** [comment]
https://medium.com/@dimanalfon
https://github.com/c4t4r
https://www.google.com/search?q=stin

**Comment by yunisangadji** [comment]
https://github.com/yunisangadji
https://medium.com/@yuniasangadji
https://www.google.com/search?q=papeda
