### ISSUE TITLE
Screenshot of organic search elements and classes

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#7]
Paste screenshot of an organic search result of a Google SERP from you search, .e.g.
![image](https://github.com/dudung/lecture-notes/assets/7240685/f2141658-db22-4f8f-a9e4-5d7f646af657)

**Comment by Antara000** [comment]
![tugas 7](https://github.com/dudung/lecture-notes/assets/144425065/4cc7e076-2fde-4d67-9092-79aae1240e42)

**Comment by CriticalOlymp** [comment]
![Screenshot 2023-10-20 101342](https://github.com/dudung/lecture-notes/assets/144425203/03cd960e-a97a-42f3-ba38-7da513fadbb1)

**Comment by afrozhie** [comment]
![Screenshot 2023-10-20 100229](https://github.com/dudung/lecture-notes/assets/116063782/25c01625-173c-4185-97a5-3c0647a35326)

**Comment by CyberianRonin** [comment]
![Screenshot (377)](https://github.com/dudung/lecture-notes/assets/122846418/6102582c-6d57-42a9-9afd-8917bf50c93e)

**Comment by bahrudinz** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425269/70f1ba3a-da71-4631-9e85-0707180fb2a1)

**Comment by IZAN0R** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424895/e5e67028-28f4-4ff3-a1dc-1ceafe526635)

**Comment by birongzah** [comment]
<img width="1466" alt="Screenshot 2023-10-20 at 10 27 30" src="https://github.com/dudung/lecture-notes/assets/144424494/d8c287d1-7ec8-4bf0-9d2a-04233a5133d3">

**Comment by NeganSmith92** [comment]
<img width="953" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425116/ac3f6087-5d51-4263-938e-22cb18dfb811">

**Comment by NerdyVandheka** [comment]
![Screenshot 2023-10-20 102747](https://github.com/dudung/lecture-notes/assets/144425376/906d1bcb-6322-40c8-852b-9bc07215e0c6)

**Comment by narapatimulia** [comment]
![Screenshot 2023-10-20 103012](https://github.com/dudung/lecture-notes/assets/144424964/c5c01325-d969-4a46-a3a5-df67bad98669)

**Comment by Ptolemu5** [comment]
![Screenshot 2023-10-20 103037](https://github.com/dudung/lecture-notes/assets/144424941/c199ce57-a07c-448f-82fb-44cded980233)

**Comment by Ptolemu5** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424941/c9f819d1-4a84-403f-b2ca-c3e17432f3cf)

**Comment by charlesmana** [comment]
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/114788396/d7885898-d8b2-4ef4-b2d8-6210faf63a35">

**Comment by yunoooo111** [comment]
![Uploading guluscraping.png…]()

**Comment by tegarhermans** [comment]
![Screenshot_6](https://github.com/dudung/lecture-notes/assets/144425283/d99e7e16-9f7e-4501-93e4-b033782fd918)

**Comment by yunoooo111** [comment]
![guluscraping](https://github.com/dudung/lecture-notes/assets/113901717/e045f9ce-0287-4aec-8cf3-acde9123966a)

**Comment by ayodyaadhi01** [comment]
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/144425145/a796207b-45d2-4710-8361-5df57e991b66">

**Comment by MazamGanendra** [comment]
![medium](https://github.com/dudung/lecture-notes/assets/144425268/41de4438-86ed-411f-8651-b252ab5f03eb)

**Comment by irhwam** [comment]
<img width="960" alt="Screenshot 2023-10-20 101611" src="https://github.com/dudung/lecture-notes/assets/144425029/7a7a6e8a-47f1-4079-851b-4abda94214b8">

**Comment by c4t4r** [comment]
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/122764330/4efe9870-dcb3-4e0b-b286-90310ef9b372">

**Comment by yunisangadji** [comment]
<img width="960" alt="image" src="https://github.com/dudung/lecture-notes/assets/145080762/a8995381-5381-4adc-9de3-2d12fe01d727">

**Comment by ayarayenima** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144424497/894c296e-b9ac-43a5-97e1-d370e48192ae)

**Comment by AKS4R4** [comment]
![image](https://github.com/dudung/lecture-notes/assets/144425016/5fb6f29a-20d4-41b1-a4bf-7da280b827fc)
