### ISSUE TITLE
Styles and elements for an organic result

### ISSUE THREAD

**Issue by dudung** [dudung/lecture-notes#9]
Write from you SERP the styles and elements for an organic search result
+ title, e.g. `LC20lb MBeuO DKV0Md > h3`
+ link
+ description
+ display link

**Comment by charlesmana** [comment]
- title LC20lb MBeuO DKV0Md
- link qLRx3b tjvcx GvPZzd cHaqb
- description VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac
- display link VuuXrf

**Comment by afrozhie** [comment]
* LC20lb MBeuO DKV0Md > h3
* UWckNb > a
* VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf > span
* qLRx3b tjvcx GvPZzd cHaqb > cite

**Comment by CriticalOlymp** [comment]
- Title = LC20lb MBeuO DKV0M> h3

- Link = UWckNb > a

- Discription = kb0PBd cvP2Ce > div

- display link = qLRx3b tjvcx GvPZzd cHaqb > cite

**Comment by CyberianRonin** [comment]
title : srKDX.cvP2Ce
link : LC20lb MBeuO DKV0Md
description : kb0PBd cvP2Ce ieodic
display link : LC20lb MBeuO DKV0Md

**Comment by NerdyVandheka** [comment]
Tittle LC20lb MBeuO DKV0Md > h3
Link VuuXrf > span
Description VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac > div
Display Link qLRx3b tjvcx GvPZzd cHaqb > cite

**Comment by tegarhermans** [comment]
- title : <h3 class="LC20lb MBeuO DKV0Md">Chairul Tanjung - Wikipedia bahasa Indonesia ...</h3>

- link : <span class="VuuXrf">Wikipedia</span>

- description : <div class="VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac"><span>Prof. Dr. (H.C.). drg. H. <em>Chairul Tanjung</em>, M.B.A. (Ejaan Soewandi: <em>Chairul Tandjung</em>, lahir 18 Juni 1962) adalah pengusaha asal Indonesia.</span></div>

- display link : <cite class="qLRx3b tjvcx GvPZzd cHaqb" role="text">https://jv.wikipedia.org<span class="dyjrff ob9lvb" role="text"> › wiki › C...</span></cite>

**Comment by MazamGanendra** [comment]
Title : LC20lb MBeuO DKV0Md >h3
Link : UWckNB >a
Description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac > div
Display Link : qLRx3b tjvcx GvPZzd cHaqb > cite

**Comment by Ptolemu5** [comment]
title, LC20lb MBeuO DKV0Md . h3
link, UWckNb >a
description, VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf >div
display link, tjvcx GvPZzd cHaqb >cite

**Comment by ayodyaadhi01** [comment]
title : LC20lb MBeuO DKV0Md >h3
link : VuuXrf >span
description : kb0PBd cvP2Ce ieodic >div
display link : qLRx3b tjvcx GvPZzd cHaqb >cite

**Comment by NeganSmith92** [comment]
title : LC20lb MBeuO DKV0Md > h3
link : VuuXrf > a
description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf > span
display link : tjvcx GvPZzd cHaqb > cite

**Comment by yunoooo111** [comment]
title : LC20lb MBeuO DKV0Md >h3
link : byrV5b
description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf > div
display link : VuuXrf

**Comment by irhwam** [comment]
title: LC20lb MBeuO DKV0Md
link: byrV5b
desc: VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf
display link: tjvcx GvPZzd cHaqb

**Comment by birongzah** [comment]
title : LC20lb MBeuO DKV0Md
link : VuuXrf
description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac
display link : qLRx3b tjvcx GvPZzd cHaqb

**Comment by IZAN0R** [comment]
Title : LC20lb.MBeuO.DKV0Md
Link : yuRUbf
Description : VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf > span
Display Link : g .yuRUbf .NJjxre .tjvcx

**Comment by c4t4r** [comment]
title: LC20lb MBeuO DKV0Md
link: a[jsname='UWckNb']
description: VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf > span
display link: g yuRUbf NJjxre tjvcx

**Comment by narapatimulia** [comment]
title : LC20lb MBeuO DKV0Md
link : VuuXrf
description : "VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac"><span>
display link : qLRx3b tjvcx GvPZzd cHaqb

**Comment by bahrudinz** [comment]
Title : LC20lb MBeuO DKV0Md > h3
Link : VuuXrf > a
Description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf > span
Display link : qLRx3b tjvcx GvPZzd cHaqb > cite

**Comment by Antara000** [comment]
Title : .LC20lb >h3
Link : .qLRx3b >cite
Description : .g .VwiC3b >span
Display link : .g .yuRUbf .NJjxre .tjvcx > cite

**Comment by ayarayenima** [comment]
- Title : LC20lb MBeuO DKV0Md <h3>
- Link : UWckNb <a>
- Description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac <span>
- Display Link : qLRx3b tjvcx GvPZzd cHaqb <cite>

**Comment by yunisangadji** [comment]
Title : LC20lb MBeuO DKV0Md >h3
Link : qLRx3b >cite
Description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac >span
Display Link : qLRx3b tjvcx GvPZzd cHaqb >cite

**Comment by Kodhil** [comment]
1.21181092
2.soeharto-Wikipedia Indoensia
3.wikipedia
4.Jenderal Besar TNI H. M. Soeharto, adalah Presiden kedua Indonesia yang menjabat dari tahun 1967 sampai 1998, menggantikan Soekarno. [Wikipedia](https://id.wikipedia.org/wiki/Soeharto)
5.https://id.wikipedia.org/wiki/Soeharto
